
open_collective : freecad
github : FreeCAD

custom : [
    'https://www.paypal.com/donate/?hosted_button_id=M3Z8BGW6DB69Q' ,
    'https://donate.stripe.com/14k3ei9TYgwFclq145' ,
    'https://wiki.freecad.org/Donate'
]